---
- name: Install Miniconda3 
  hosts: all
  become: true
  vars:
    ansible_ssh_private_key_file: /root/.ssh/id_rsa
    ansible_user: root
    ansible_port: 22
    miniconda_name: "Miniconda3-py37_23.1.0-1-Linux-x86_64.sh"

  tasks:
    - name: download package
      get_url:
        url: "https://repo.anaconda.com/miniconda/{{ miniconda_name }}"
        dest: "/tmp/{{  miniconda_name }}"

    - name: install miniconda
      shell: /usr/bin/sh "/tmp/{{ miniconda_name }}" -b -p /usr/local/miniconda3
      args:
        chdir: /tmp

    - name: add to path
      shell: sed -i '$a\export PYTHON=/usr/local/miniconda3/bin' /etc/bashrc

    - name: add to path
      shell: sed -i '$a\export PATH=$PYTHON:$PATH' /etc/bashrc
