- name: Install and Configure MySQL 5.7
  hosts: all
  become: yes
  roles:
    - geerlingguy.mysql

  vars:
    ansible_ssh_private_key_file: /root/.ssh/id_rsa
    ansible_user: root
    ansible_port: 22

    mysql_version: "5.7"
    mysql_root_password: ""
    mysql_root_password_update: true
    mysql_bind_address: "127.0.0.1"
    mysql_port: "3306"
    mysql_datadir: "/var/lib/mysql"
    mysql_disable_log_bin: true
    mysql_enabled_on_startup: true
